name: nutriticket
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  image_picker: ^1.1.0
  http: ^1.2.0
  mime: ^1.0.5
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  
  # --- ðŸ‘‡ LÃNEAS A AÃ‘ADIR (CON LA CORRECCIÃ“N) ---
  firebase_storage: ^11.6.9  # Para subir imÃ¡genes
  intl: ^0.20.2             # <--- CORRIGE A ESTA VERSIÃ“N
  # --- ðŸ‘† FIN DE LAS LÃNEAS A AÃ‘ADIR ---

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatars/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  # âœ… LÃNEA AÃ‘ADIDA: Elimina la transparencia solo para los Ã­conos de iOS
  remove_alpha_ios: true

